language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer install -n

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    rooms:
      secure: FhbMsWVYyKuWFs/aU4B5NF6MQYvEei+BiTe/6Ussoxo6DCFEfajwQjIFgamjS0h5fGkgql+WAH0d+idkTRQ16ali46yLZWQKXh4dB0essmIr8mBEtrCO9ZIT7YgMQ3ZWvvKi/QaQGiTwqQ+klZjdomXDB9i3JCZXuPIUL+NQ6vuNw2Sqr7krnDI6ugQd6u2E97pthJQFvul/3HSwYGNZnWFuK1ZdYAx7gDz4TuYZoPPFtl2dcq1ZdogOUFn5ZG+f4+Nlt8Tgv8jR7cB/bwAW4lQ+qCCawTBUeglpi6jaOdM9HIoe3VkCB4/4hkJzltk8knzOSvE1aHoamtysGOTBEc/LKEfD5CVAxzl2r0Knzfg2gu4X4JbqvU6bNWcESIdlEGAZ+6ML6cx1x2sZtUiDWbT4IfvXqJtFXLAxs/5kNdkDa9OnRlX/2APiVcym6qD1+ba2tP7SJ5iG3kknGDkSBzta2pjganDtKcmsBgYp0Qj6eyCcPoz2qBlWeAE3uKh3qM1LXjf3yu5iK1Rb0YPzpE/Ieq+GgnwlYZtEQ+sz9MTHTuCcGO/JfnQ/B7EAXl3oOgjkVvPEtiFXZps9CQwbj+xEsKQOr9W5K6mXCJxNdGGVS5NtN2zODrj9VP+QdAirPzMQjEIVmOu4+1yHUcl7a9EBmdXrqN3aEClHkjk7P/Y=
